export const getDashboardComponents = (userId) => [
    {
        id: 1,
        name: "Profile",
        icon: "ImProfile",
        link: `/dashboard/profile/${userId}`,
        role: "user",
    },
    {
        id: 2,
        name: "Notifications",
        icon: "IoNotificationsCircleOutline",
        link: "/dashboard/notifications",
        role: "all",
    },
    {
        id: 3,
        name: "Sell Products",
        icon: "MdOutlineSell",
        link: "/dashboard/sell_product/create_product",
        role: "user",
    },
    {
        id: 4,
        name: "Rent Products",
        icon: "IoCartOutline",
        link: "/dashboard/rent_product/create_product",
        role: "user",
    },
    {
        id: 5,
        name: "Settings",
        icon: "IoSettingsOutline",
        link: "/dashboard/settings",
        role: "user",
    },
    {
        id: 6,
        name: "Admin Profile",
        icon: "ImProfile",
        link: `/dashboard/admin/profile/${userId}`,
        role: "admin",
    },
    {
        id: 7,
        name: "Admin Notifications",
        icon: "IoNotificationsCircleOutline",
        link: "/dashboard/admin/notifications",
        role: "admin",
    },
    {
        id: 8,
        name: "Admin Dashboard",
        icon: "MdOutlineSell",
        link: `/dashboard/admin/dashboard/${userId}`,
        role: "admin",
    },
    {
        id: 9,
        name: "Settings",
        icon: "IoSettingsOutline",
        link: "/dashboard/settings",
        role: "admin",
    },
    {
        id: 10,
        name: "Verify",
        icon: "GoCheckbox",
        link: "/dashboard/verify_user",
        role: "user",
    },
    {
        id: 11,
        name: "Products",
        icon: "AiTwotoneShopping",
        link: "/dashboard/user/products",
        role: "user",
    },

];
